spring:
  application:
    name: service-two
# 向注册中心注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:8081
server:
  port: 8089
  session:
      timeout: 36000