package com.liuzhiqiang.mapper.sys;

import com.liuzhiqiang.domain.sys.SysDepartment;
import com.liuzhiqiang.domain.sys.vo.SysDepartmentVo;
import com.liuzhiqiang.until.BrushUtils;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface SysDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Nov 27 09:49:33 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Nov 27 09:49:33 CST 2018
     */
    int insert(SysDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Nov 27 09:49:33 CST 2018
     */
    int insertSelective(SysDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Nov 27 09:49:33 CST 2018
     */
    SysDepartmentVo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Nov 27 09:49:33 CST 2018
     */
    int updateByPrimaryKeySelective(SysDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_department
     *
     * @mbg.generated Tue Nov 27 09:49:33 CST 2018
     */
    int updateByPrimaryKey(SysDepartment record);

    List<SysDepartmentVo> listDepartment(BrushUtils brushUtils);

    List<SysDepartmentVo> departmentListAll();
}