package com.liuzhiqiang.mapper.sys;

import com.liuzhiqiang.domain.sys.SysPermission;
import com.liuzhiqiang.domain.sys.vo.SysPermissionVo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface SysPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    int insert(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    int insertSelective(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    SysPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    int updateByPrimaryKeySelective(SysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    int updateByPrimaryKey(SysPermission record);


    //根据父级id查询子级全权限
    List<SysPermissionVo> listPermission(@Param("userId") Long userId);

    List<SysPermissionVo> companyListPermission();

    List<SysPermissionVo> perList(@Param("str") String str);

    List<SysPermission> getSysPermissionSun(@Param("parentId") Long id);
}