package com.liuzhiqiang.mapper.sys;

import com.liuzhiqiang.domain.sys.SysRole;
import com.liuzhiqiang.domain.sys.vo.SysRoleVo;
import com.liuzhiqiang.until.BrushUtils;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface SysRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Tue Nov 27 09:50:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Tue Nov 27 09:50:03 CST 2018
     */
    int insert(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Tue Nov 27 09:50:03 CST 2018
     */
    int insertSelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Tue Nov 27 09:50:03 CST 2018
     */
    SysRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Tue Nov 27 09:50:03 CST 2018
     */
    int updateByPrimaryKeySelective(SysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role
     *
     * @mbg.generated Tue Nov 27 09:50:03 CST 2018
     */
    int updateByPrimaryKey(SysRole record);

    List<SysRoleVo> listRole(BrushUtils brushUtils);

    SysRole getRoleInfo(@Param("id") Long id);

    List<SysRoleVo> listRoleDepartment(@Param("departmentId") Long departmentId);
}