server:
  port: 8080 # 注册中心占用8080端口
eureka:
  instance:
    hostname: 123.206.19.217
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
