package com.liuzhiqiang.domain.sys;

import lombok.Data;

import java.util.Date;

@Data
public class SysPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.id
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.per_level
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    private Integer perLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.per_name
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    private String perName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.permission_code
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    private String permissionCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.per_type
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    private Integer perType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.per_img
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    private String perImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.per_url
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    private String perUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.sort
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.parent_id
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.del_flag
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    private Integer delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.create_by
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.create_date
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.update_by
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    private Long updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.update_date
     *
     * @mbg.generated Tue Nov 27 09:49:48 CST 2018
     */
    private Date updateDate;
}