package com.liuzhiqiang.domain.sys;

import lombok.Data;

import java.util.Date;


@Data
public class SysUserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.id
     *
     * @mbg.generated Tue Nov 27 09:50:51 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.user_id
     *
     * @mbg.generated Tue Nov 27 09:50:51 CST 2018
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.role_id
     *
     * @mbg.generated Tue Nov 27 09:50:51 CST 2018
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.department_id
     *
     * @mbg.generated Tue Nov 27 09:50:51 CST 2018
     */
    private Long departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.create_by
     *
     * @mbg.generated Tue Nov 27 09:50:51 CST 2018
     */
    private Long createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.create_date
     *
     * @mbg.generated Tue Nov 27 09:50:51 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.update_by
     *
     * @mbg.generated Tue Nov 27 09:50:51 CST 2018
     */
    private Long updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.update_date
     *
     * @mbg.generated Tue Nov 27 09:50:51 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.del_flag
     *
     * @mbg.generated Tue Nov 27 09:50:51 CST 2018
     */
    private Integer delFlag;
}