eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: GatewayService
server:
  port: 8083
zuul:
  routes:
    ServiceOne:
      path: /api-a/**
      serviceId: ServiceOne
    ServiceTwo:
      path: /api-b/**
      serviceId: ServiceTwo

