spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/2425358736/file
          searchPaths: respo
          username: 2425358736@qq.com
          password: lzq199528
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/  #注册中心地址
  instance:
    hostname: localhost
    instance-id: http://localhost:19090
server:
  port: 19090


