spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/2425358736/file
          searchPaths: service-one
          username: 2425358736@qq.com
          password: lzq199528
      label: master
eureka:
  client:
    serviceUrl:
      defaultZone: http://123.206.19.217:8080/eureka/  #注册中心地址
  instance:
    hostname: 123.206.19.217
    instance-id: http://123.206.19.217:18888
server:
  port: 18888


